apiVersion: v1
kind: Secret
metadata:
  name: luishuaraca-api-secret
  namespace: luishuaraca-ns
  labels:
    app: luishuaraca-api
type: Opaque
data:
  username: c2E=         
  password: cGFzc3dvcmQ=   