apiVersion: v1
kind: Secret
metadata:
  name: luishuaraca-secret
  namespace: luishuaraca-ns
labels:
APP: LuisHuaraca-api 

type:  Opaque
stringData:
  SECRET_USERNAME: [EMAIL_ADDRESS]
  PASSWORD: [PASSWORD]